In [1]:
import os
import pandas as pd
import numpy as np
import random


def listdir(path, list_name):  # 传入存储的list
    for file in os.listdir(path):
        file_path = os.path.join(path, file)
        if os.path.isdir(file_path):
            listdir(file_path, list_name)
        else:
            list_name.append(file_path)


file_paths = []
listdir("F:\\gitworkspace\\python\\e-nose-cnn\\draw_test", file_paths)
#print(file_paths)

for i in file_paths:
    # excel_data = pd.read_csv(i,sep=',',dtype=np.object,userows=[44, 104])
    # excel_data = pd.read_csv(i,sep=' ',dtype=np.object,skiprows=52,nrows=200,header=None)
    try:
        data = pd.read_csv(i, sep='\t', dtype=np.object,
            skiprows=52, header=None, engine='python')
        data = data.loc[0:119]
        # data = data[range(10)]
        data = data[random.sample(range(0,10),10)]
        # print(data)
        data.to_csv(os.path.join("F:\\gitworkspace\\python\\e-nose-cnn\\draw_test", "{0[4]}-1.csv".format(
            i.split("\\"))), encoding='utf_8_sig', index=False, header=1)  # 单纯utf8编码用excel打开会乱码
    except Exception as e:
        print(i)

F:\gitworkspace\python\e-nose-cnn\draw_test\csvtran.ipynb
F:\gitworkspace\python\e-nose-cnn\draw_test\draw_test.csv
F:\gitworkspace\python\e-nose-cnn\draw_test\draw_test.npy
F:\gitworkspace\python\e-nose-cnn\draw_test\nos2csv.ipynb
F:\gitworkspace\python\e-nose-cnn\draw_test\tran.csv


In [57]:
import numpy as np
import pandas as pd

index = [0,2,1,3]
print(index)
a = np.array([[1,2,3],[2,3,4],[1,6,5], [9,3,4],[2,3,5],[6,7,4],[1,7,4],[3,7,4]])
index2 = list(range(4))
# index2 = pd.DataFrame(index2)
print(index2)
for j in range(2):
    index2 = [i + 4*j for i in index2]
    index = [i + 4*j for i in index]
    a[index] = a[index2]
print(a)

[0, 2, 1, 3]
[0, 1, 2, 3]
[[1 2 3]
 [1 6 5]
 [2 3 4]
 [9 3 4]
 [2 3 5]
 [1 7 4]
 [6 7 4]
 [3 7 4]]
