In [1]:
import pandas as pd
import numpy as np

train_x = pd.read_csv( "F:\\gitworkspace\\python\\e-nose-cnn\\nos-data\\3times7class\\trainset2.csv")
train_y = pd.read_excel( "F:\\gitworkspace\\python\\e-nose-cnn\\nos-data\\3times7class\\train_label2.xlsx")

test_x = pd.read_csv( "F:\\gitworkspace\\python\\e-nose-cnn\\nos-data\\3times7class\\testset2.csv")
test_y = pd.read_excel( "F:\\gitworkspace\\python\\e-nose-cnn\\nos-data\\3times7class\\test_label2.xlsx")

# train_x = train_x.fillna(method='ffill')
# test_x = test_x.fillna(method='ffill')

np.save('F:\\gitworkspace\\python\\e-nose-cnn\\nos-data\\3times7class\\trainset2.npy', train_x)
np.save('F:\\gitworkspace\\python\\e-nose-cnn\\nos-data\\3times7class\\trainlabel2.npy', train_y)

np.save('F:\\gitworkspace\\python\\e-nose-cnn\\nos-data\\3times7class\\testset2.npy', test_x)
np.save('F:\\gitworkspace\\python\\e-nose-cnn\\nos-data\\3times7class\\testlabel2.npy', test_y)

In [2]:
data = np.load('F:\\gitworkspace\\python\\e-nose-cnn\\codedata\\3times\\dataset.npy')
print(data)

[[0.9867 0.9955 1.0149 ... 0.6099 0.6094 0.6088]
 [0.9993 0.999  1.0882 ... 1.7726 1.7722 1.7768]
 [0.9921 1.0022 1.0137 ... 0.6295 0.6289 0.6283]
 ...
 [0.9821 0.9817 1.0529 ... 4.0113 4.0058 3.9953]
 [0.9874 0.9979 0.9981 ... 2.7219 2.7222 2.7208]
 [1.0017 1.0104 1.0387 ... 1.0126 1.0118 1.0125]]


In [2]:
train_x = np.load('F:\\gitworkspace\\python\\e-nose-cnn\\train\\trainset.npy')
train_y = np.load('F:\\gitworkspace\\python\\e-nose-cnn\\train\\trainlabel.npy')

test_x = np.load('F:\\gitworkspace\\python\\e-nose-cnn\\test\\testset.npy')
test_y = np.load('F:\\gitworkspace\\python\\e-nose-cnn\\test\\testlabel.npy')
print(train_x)
print(train_y)



[[0.9934 1.0726 1.006  ... 0.5418 0.5416 0.5418]
 [0.9947 1.0439 1.3713 ... 3.1052 3.1018 3.0906]
 [1.0009 1.0555 0.9944 ... 0.5019 0.5016 0.5025]
 ...
 [0.9865 0.986  1.039  ... 2.2265 2.2268 2.2278]
 [0.9654 0.9804 1.0205 ... 2.7179 2.7189 2.7182]
 [0.9983 1.0013 0.9993 ... 0.9782 0.9775 0.9783]]
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
