In [1]:
import pandas as pd
import numpy as np

train_x = pd.read_csv( "F:\\gitworkspace\\python\\e-nose-cnn\\train\\train.csv")
train_y = pd.read_excel( "F:\\gitworkspace\\python\\e-nose-cnn\\train\\train_label.xlsx")

test_x = pd.read_csv( "F:\\gitworkspace\\python\\e-nose-cnn\\test\\test.csv")
test_y = pd.read_excel( "F:\\gitworkspace\\python\\e-nose-cnn\\test\\test_label.xlsx")

train_x = train_x.fillna(method='ffill')
test_x = test_x.fillna(method='ffill')

np.save('F:\\gitworkspace\\python\\e-nose-cnn\\train\\trainset.npy', train_x)
np.save('F:\\gitworkspace\\python\\e-nose-cnn\\train\\trainlabel.npy', train_y)

np.save('F:\\gitworkspace\\python\\e-nose-cnn\\test\\testset.npy', test_x)
np.save('F:\\gitworkspace\\python\\e-nose-cnn\\test\\testlabel.npy', test_y)

In [5]:
train_y = pd.read_excel( "F:\\gitworkspace\\python\\e-nose-cnn\\train\\train_label.xlsx")
print(train_y.size())

TypeError: 'numpy.int32' object is not callable

In [2]:
train_x = np.load('F:\\gitworkspace\\python\\e-nose-cnn\\train\\trainset.npy')
train_y = np.load('F:\\gitworkspace\\python\\e-nose-cnn\\train\\trainlabel.npy')

test_x = np.load('F:\\gitworkspace\\python\\e-nose-cnn\\test\\testset.npy')
test_y = np.load('F:\\gitworkspace\\python\\e-nose-cnn\\test\\testlabel.npy')
print(train_x)
print(train_y)



[[0.9934 1.0726 1.006  ... 0.5418 0.5416 0.5418]
 [0.9947 1.0439 1.3713 ... 3.1052 3.1018 3.0906]
 [1.0009 1.0555 0.9944 ... 0.5019 0.5016 0.5025]
 ...
 [0.9865 0.986  1.039  ... 2.2265 2.2268 2.2278]
 [0.9654 0.9804 1.0205 ... 2.7179 2.7189 2.7182]
 [0.9983 1.0013 0.9993 ... 0.9782 0.9775 0.9783]]
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
