In [14]:
import os
import pandas as pd
import numpy as np


def listdir(path, list_name):  # 传入存储的list
    for file in os.listdir(path):
        file_path = os.path.join(path, file)
        if os.path.isdir(file_path):
            listdir(file_path, list_name)
        else:
            list_name.append(file_path)

file_paths = []
listdir("F:\\gitworkspace\\python\\e-nose-cnn\\nos-data\\3times7class\\woshu\\3", file_paths)
# print(file_paths)

data = range(120)
data = pd.DataFrame(data)
data = data.values
data = list(map(list,zip(*data)))
data = pd.DataFrame(data)
data.to_csv(os.path.join("F:\\gitworkspace\\python\\e-nose-cnn", "testnos2npy.csv"), encoding='utf_8_sig', index=False, header=0)

for i in file_paths:
    try:
        data = pd.read_csv(i, sep='\t', dtype=np.object,skiprows=52, header=None, engine='python')
        data = data.loc[0:119]
        data = data[range(10)]
        data = pd.DataFrame(data)
        data = data.values
        data = list(map(list,zip(*data)))
        data = pd.DataFrame(data)
        data.to_csv(os.path.join("F:\\gitworkspace\\python\\e-nose-cnn", "testnos2npy.csv"), encoding='utf_8_sig', index=False, header=0,mode = 'a+')#utf_8_sig
    except Exception as e:
        print(i)

df = pd.read_csv( "F:\\gitworkspace\\python\\e-nose-cnn\\testnos2npy.csv")
np.save('F:\\gitworkspace\\python\\e-nose-cnn\\testnos2npy.npy', df)
df = np.load('F:\\gitworkspace\\python\\e-nose-cnn\\testnos2npy.npy')
for i in range(6):
    


print(df)

2.0373
[[ 1.0169  1.0204  0.9989 ...  0.4454  0.4448  0.4442]
 [ 0.9798  0.976   1.0207 ... 14.6199 14.6784 14.7248]
 [ 1.0185  1.0223  0.9883 ...  0.3463  0.3456  0.3458]
 ...
 [ 0.9822  0.9826  1.0131 ...  2.0567  2.0611  2.063 ]
 [ 0.9689  0.972   0.9966 ...  2.3969  2.3981  2.3976]
 [ 1.0017  0.9993  0.987  ...  0.9447  0.9444  0.9448]]
